maclevels <- c("Mono",
               "Mac-TR",
               "Mac-IFN",
               "Mac-M1-1",
               "Mac-M1-2",
               "Mac-M2-1",
               "Mac-M2-2",
               "Mac-M2-3",
               "Mac-Cyc",
               "Mac-10",
               "Mac-11",
               "Mac-12")