maclevels <- c("Mono",
               "Mac-TR",
               "Mac-IFN",
               "Mac-M1-1",
               "Mac-M1-2",
               "Mac-M1-3",
               "Mac-M2-1",
               "Mac-M2-2",
               "Mac-M2-3",
               "Mac-Cyc-1",
               "Mac-Cyc-2",
               "Mac-12",
               "Mac-13",
               "Mac-14",
               "Mac-15",
               "Mac-16")